### ISSUE TITLE
Composer GitHub Service Hook?

### ISSUE THREAD

**Issue by philwareham** [cara-tm/pat_if_amp#3]
Hi there, I've just tagged a new pre-prerelease (0.3.6-beta) but Packagist is not auto-updating. I assume this is because you haven't created the GitHub Service Hook as yet? See [instructions at bottom of page here](https://packagist.org/about).

**Comment by cara-tm** [comment]
Please, try again.
![bump](https://user-images.githubusercontent.com/61045/27841925-68bfe8a4-6105-11e7-8184-3506bb1efd99.png)

**Comment by philwareham** [comment]
Hi, yep this works now. You can test the beta by using:

    composer require cara-tm/pat_if_amp:0.3.6-beta

Once an non-prerelease version is released all you'll need is:

    composer require cara-tm/pat_if_amp:*

This plugin is [now used](https://github.com/textpattern/textpattern-com-website/blob/master/composer.json) in the upcoming new Textoattern.com site. Cheers!

**Comment by philwareham** [comment]
When you are ready to do a 0.3.6 release let me know and I'll run through it with you. Also you'll need to add the compiled plugin `.txt` file to the release as a binary attachment (again I'll run through that with you).

Hopefully you can see the value in Composer and will add to other plugins over time.

**Comment by cara-tm** [comment]
Sure. Thanks lot Phil.
I project to read the entire (new) official AMP documentation because lot of improvements have been added since one year.
;)
