### ISSUE TITLE
Doesn't work with PHP 5.4

### ISSUE THREAD

**Issue by philwareham** [cara-tm/pat_if_amp#4]
Hi,

The plugin doesn't work in PHP 5.4 (only seems to work in PHP 5.5 onwards) and I need it to so I can launch the new Textpattern.com website. Any chance you can find a way of backporting this to 5.4.

I don't have the luxury of upgrading PHP on that server unfortunately.

**Comment by cara-tm** [comment]
Sorry I was busy.
Good catch, Phil !
Thank you.
