### ISSUE TITLE
Not sure the Packagist hook is set up

### ISSUE THREAD

**Issue by philwareham** [cara-tm/pat_if_amp#5]
Hi,

I don't think the service hook is set up properly between GitHub and Packagist for this repo. Can you confirm? Instructions here (at bottom): https://packagist.org/about

I tagged a new release on GitHub earlier today put it's not registering so at Packagist.

**Comment by cara-tm** [comment]
Updated to v 0.3.6.
It is good?

**Comment by philwareham** [comment]
Yep, that's good now thanks. Closing.

**Comment by cara-tm** [comment]
;)
